language: java

matrix:
  include:
    - jdk: openjdk8
    - jdk: openjdk9
    - jdk: openjdk10
    - jdk: openjdk11
    - os: osx
      osx_image: xcode10.1
      env: JAVA_HOME=$(/usr/libexec/java_home)

services:
  - xvfb

before_cache:
  - rm -rf $HOME/.m2/repository/uk/gov/nationalarchives/

cache:
  directories:
    - $HOME/.m2
