version: '{build}'
install:
  - cmd: SET JDK_HOME=C:\Program Files\Java\jdk11
  - cmd: SET JAVA_HOME=C:\Program Files\Java\jdk11
  - cmd: SET PATH=%JDK_HOME%\bin;%PATH%
  - cmd: mvn --version
  - cmd: java -version
build_script:
- cmd: mvn compile
test_script:
- cmd: mvn test -B
